---
- name: install redshift
  package:
    name: "{{ item }}"
    state: present
  become: yes
  become_method: sudo
  with_items:
    - "{{ redshift.base }}"

- name: install redshift-gtk
  package:
    name: "{{ item }}"
    state: present
  become: yes
  become_method: sudo
  with_items:
    - "{{ redshift.gui }}"
  when: redshift.gui_enabled

- name: make sure config dir is present
  file:
    path: "{{ redshift.conf_path }}"
    state: directory
    mode: u=rwx

- name: install redshift template
  template:
    src: "{{ item }}.j2"
    dest: "{{ redshift.conf_path }}/{{ item }}"
    owner: "{{ ansible_user }}"
    mode: 0640
  with_items:
    - redshift.conf
